Add BOF to collect Slack cookies from Slack or browser processes
trustedsec/CS-Remote-OPs-BOF pull request #25
Opened 2023-11-02 14:01 UTC by Tw1sm

This is basically a clone of the `office_tokens` BOF with very minor modifications to target the Slack `d` cookie, which can be replayed via the browser/desktop app.

2024-01-31 19:32 UTC, freefirex requested changes
Thanks for the pull, only one item I'd like to see changed

2024-01-31 19:32 UTC, freefirex commented on src/Remote/slack_cookie/entry.c
> +            index += MSVCRT$strlen((char *)(buffer + index)) - 1;
if you could flip this out to an strnlen using the remainder of the buffer to be examined as the size I'll happily accept this.

The LoadLibrary calls should also have a matching FreeLibrary call.  Msg should call out unable to load kernel32, granted if this bof started running kernel32 should already be loaded in.

2024-02-01 17:01 UTC, Tw1sm commented
@freefirex Made the suggested changes (thanks again for providing) - let me know if any other edits are needed!

2024-02-02 20:22 UTC, merged

2024-02-02 20:23 UTC, freefirex commented
Awesome :100: Merged!